// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkikjfqewtmocwdrrcdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndraWtqZnFld3Rtb2N3ZHJyY2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2MDQ2NDEsImV4cCI6MjA4MTE4MDY0MX0.5XZsfCrnG6obtLJGHqvDoAX7kSL-_m1Xf5K1wdGmKio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});